# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'IFC.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(640, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.TITTLELABEL = QtWidgets.QLabel(self.centralwidget)
        self.TITTLELABEL.setGeometry(QtCore.QRect(10, 20, 621, 41))
        self.TITTLELABEL.setStyleSheet("color: rgb(0, 170, 127);\n"
"font: 75 36pt \"MS Shell Dlg 2\";")
        self.TITTLELABEL.setAlignment(QtCore.Qt.AlignCenter)
        self.TITTLELABEL.setObjectName("TITTLELABEL")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 90, 611, 21))
        self.frame.setStyleSheet("background-color: rgb(225, 225, 225);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(90, 0, 61, 21))
        self.label_2.setStyleSheet("color: rgb(0, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(290, 0, 61, 21))
        self.label_3.setStyleSheet("color: rgb(0, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(440, 0, 61, 21))
        self.label_4.setStyleSheet("color: rgb(0, 170, 127);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        self.NOMBRESV = QtWidgets.QLabel(self.centralwidget)
        self.NOMBRESV.setGeometry(QtCore.QRect(100, 120, 91, 21))
        self.NOMBRESV.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.NOMBRESV.setObjectName("NOMBRESV")
        self.IPSV = QtWidgets.QLabel(self.centralwidget)
        self.IPSV.setGeometry(QtCore.QRect(280, 120, 71, 21))
        self.IPSV.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.IPSV.setObjectName("IPSV")
        self.DOWNLABEL = QtWidgets.QLabel(self.centralwidget)
        self.DOWNLABEL.setGeometry(QtCore.QRect(470, 120, 51, 21))
        self.DOWNLABEL.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.DOWNLABEL.setObjectName("DOWNLABEL")
        self.DOWNICON = QtWidgets.QLabel(self.centralwidget)
        self.DOWNICON.setGeometry(QtCore.QRect(440, 120, 31, 21))
        self.DOWNICON.setStyleSheet("image: url(:/newPrefix/delete.png);")
        self.DOWNICON.setText("")
        self.DOWNICON.setScaledContents(False)
        self.DOWNICON.setObjectName("DOWNICON")
        self.UPICON = QtWidgets.QLabel(self.centralwidget)
        self.UPICON.setGeometry(QtCore.QRect(440, 120, 31, 21))
        self.UPICON.setStyleSheet("image: url(:/newPrefix/check.png);")
        self.UPICON.setText("")
        self.UPICON.setObjectName("UPICON")
        self.UPLABEL = QtWidgets.QLabel(self.centralwidget)
        self.UPLABEL.setEnabled(True)
        self.UPLABEL.setGeometry(QtCore.QRect(470, 120, 61, 21))
        self.UPLABEL.setCursor(QtGui.QCursor(QtCore.Qt.OpenHandCursor))
        self.UPLABEL.setAutoFillBackground(False)
        self.UPLABEL.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 12pt \"MS Shell Dlg 2\";")
        self.UPLABEL.setObjectName("UPLABEL")
        self.UPICON.raise_()
        self.TITTLELABEL.raise_()
        self.frame.raise_()
        self.NOMBRESV.raise_()
        self.IPSV.raise_()
        self.DOWNLABEL.raise_()
        self.DOWNICON.raise_()
        self.UPLABEL.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAgregar_IP = QtWidgets.QAction(MainWindow)
        self.actionAgregar_IP.setObjectName("actionAgregar_IP")
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuMenu.addAction(self.actionAgregar_IP)
        self.menuMenu.addAction(self.actionAbout)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.TITTLELABEL.setText(_translate("MainWindow", "Evolution Monitor"))
        self.label_2.setText(_translate("MainWindow", "Servidor"))
        self.label_3.setText(_translate("MainWindow", "IP"))
        self.label_4.setText(_translate("MainWindow", "ESTADO"))
        self.DOWNLABEL.setText(_translate("MainWindow", "DOWN"))
        self.UPLABEL.setText(_translate("MainWindow", "ONLINE"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAgregar_IP.setText(_translate("MainWindow", "Agregar servidor"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
import iconos_rc
